CREATE DATABASE rentalmovie;
USE rentalmovie;

CREATE TABLE genre
(id BIGINT NOT NULL AUTO_INCREMENT,
genre VARCHAR(30) NOT NULL, 
PRIMARY KEY(id),
UNIQUE(genre)); 

CREATE TABLE actors
(id BIGINT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(30) NOT NULL, 
last_name VARCHAR(30) NOT NULL, 
PRIMARY KEY(id),
UNIQUE(first_name, last_name)); 

CREATE TABLE promotion
(id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
value DECIMAL(10,2) NOT NULL, 
promotion_days_number SMALLINT NOT NULL,
PRIMARY KEY(id),
UNIQUE(name)); 

CREATE TABLE movie
(id BIGINT NOT NULL AUTO_INCREMENT,
genre_id BIGINT NOT NULL,
promotion_id BIGINT NOT NULL,
title VARCHAR(200) NOT NULL, 
director VARCHAR(80) NOT NULL,
production_year VARCHAR(4) NOT NULL,
description VARCHAR(400),
PRIMARY KEY(id),
FOREIGN KEY(promotion_id) REFERENCES promotion(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(genre_id) REFERENCES genre(id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE starring 
(actors_id BIGINT NOT NULL,
movie_id BIGINT NOT NULL,
PRIMARY KEY (actors_id, movie_id),
FOREIGN KEY (actors_id) REFERENCES actors(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (movie_id) REFERENCES movie(id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE employee
(id BIGINT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(30) NOT NULL, 
last_name VARCHAR(30) NOT NULL, 
phone_number VARCHAR(40) NOT NULL,
email VARCHAR(60) NOT NULL,
password VARCHAR(32) NOT NULL,
pw_change_key VARCHAR(30)DEFAULT NULL,
pw_change_date DATETIME DEFAULT NULL,
PRIMARY KEY(id),
UNIQUE(first_name, last_name, email)); 

CREATE TABLE roles
(id BIGINT NOT NULL AUTO_INCREMENT,
role VARCHAR(20) NOT NULL,
PRIMARY KEY(id),
UNIQUE(role)); 

CREATE TABLE employee_roles 
(employee_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
PRIMARY KEY(employee_id, role_id),
CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE client
(id BIGINT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(30) NOT NULL, 
last_name VARCHAR(30) NOT NULL,
pesel VARCHAR(11) NOT NULL,
city VARCHAR(30) NOT NULL,
street VARCHAR(60) NOT NULL, 
phone_number VARCHAR(40) NOT NULL,
email VARCHAR(60) NOT NULL,
PRIMARY KEY(id),
UNIQUE(first_name, last_name, pesel)); 

CREATE TABLE receipt
(id BIGINT NOT NULL AUTO_INCREMENT,
price DECIMAL(10,2),
pay_date DATETIME,
bill_number VARCHAR(10)NOT NULL,
PRIMARY KEY(id),
UNIQUE(bill_number)); 

CREATE TABLE movie_copy
(id BIGINT NOT NULL AUTO_INCREMENT,
movie_id BIGINT NOT NULL,
serial_number VARCHAR(20) NOT NULL,
condition_info VARCHAR(150) DEFAULT 'OK',
availability BOOLEAN NOT NULL DEFAULT 1,
PRIMARY KEY(id),
FOREIGN KEY(movie_id) REFERENCES movie(id) ON DELETE CASCADE ON UPDATE CASCADE,
UNIQUE(serial_number));

CREATE TABLE renting_registry
(id BIGINT NOT NULL AUTO_INCREMENT,
employee_id BIGINT NOT NULL, 
client_id BIGINT NOT NULL, 
receipt_id BIGINT NOT NULL,
movie_copy_id BIGINT NOT NULL, 
rent_date DATETIME NOT NULL, 
return_date DATETIME NOT NULL,
comment VARCHAR(255),
PRIMARY KEY(id),
FOREIGN KEY(employee_id) REFERENCES employee(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(client_id) REFERENCES client(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(movie_copy_id) REFERENCES movie_copy(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(receipt_id) REFERENCES receipt(id) ON DELETE CASCADE ON UPDATE CASCADE);
